### ISSUE TITLE
Revisar la semantica y minificar archivos css y js

### ISSUE THREAD

**Issue by juanelojga** [00dav00/marcadores-minimal#20]
Para mejorar el rendimiento en la carga de la página web seria recomendable minificar los archivos css y js utilizados por los iframes en producción.
Para cumplir las reglas que imparte el framework bootstrap, los iframes o vistas deben cumplir con la semantica del framework.
-  Prioritariamente se debe revisar que no exista una class "col-*" inmediatamente despues de una class "col-*". El padding que contienen estas clases hace que aparezca un espacio lateral derecho.

**Comment by 00dav00** [comment]
Cambio esto a prioritario porque no solo ayuda a la velocidad sino que sin esto los PRs son ilegibles lo cual puede implicar que se nos vayan errores @juanelojga
